"""Generate Validation/MavF15BaumannTableViiData.cs from the two transcription files beside this
script (baumann_table_vii_part1.txt / _part2.txt).

Each value is written exactly as printed (the printed decimal, parsed once); an illegible field is
written as double.NaN and its note carries the printed glyphs. Row notes are copied verbatim.

Usage: python gen_table_vii.py <path to MavF15BaumannTableViiData.cs>
"""
import json
import sys


def load(path, ncol):
    rows = []
    for line in open(path, encoding='utf-8'):
        if not line.strip():
            continue
        body, _, note = line.partition('#')
        t = body.split()
        vals = t[1:1 + ncol]
        assert len(vals) == ncol, line
        rows.append((int(t[0]), vals, note.strip()))
    assert [r[0] for r in rows] == list(range(1, 202)), 'rows must be 1..201 in order'
    return rows


def cs(v):
    if v == 'NaN':
        return 'double.NaN'
    x = float(v)
    s = repr(x)
    return s if ('.' in s or 'e' in s) else s + '.0'


p1 = load('baumann_table_vii_part1.txt', 4)
p2 = load('baumann_table_vii_part2.txt', 5)

out = []
w = out.append
w('// <auto-generated>')
w('// Generated by Docs/Reference/Data/F15/table_vii/gen_table_vii.py from the verified transcription')
w('// of Baumann (DTIC ADA217366) Table VII, PDF pp.124-133. Values are the printed decimals; NaN marks')
w('// a field illegible in the scan. Do not hand-edit: correct the transcription and regenerate.')
w('// </auto-generated>')
w('namespace MaverickFresh.FlightDynamics.Validation')
w('{')
w('    public static partial class MavF15BaumannTableVii')
w('    {')
w('        // point, stabilator deg, alpha deg, sideslip deg, roll rate rad/s')
w('        private static readonly double[,] Part1Values =')
w('        {')
for n, v, _ in p1:
    w('            { %d, %s },' % (n, ', '.join(cs(x) for x in v)))
w('        };')
w('')
w('        // point, pitch rate rad/s, yaw rate rad/s, pitch angle deg, bank angle deg, true velocity kft/s')
w('        private static readonly double[,] Part2Values =')
w('        {')
for n, v, _ in p2:
    w('            { %d, %s },' % (n, ', '.join(cs(x) for x in v)))
w('        };')
w('')
w('        private static readonly string[] Part1Notes =')
w('        {')
for n, _, note in p1:
    if note:
        w('            %s, %s,' % (json.dumps(str(n)), json.dumps(note)))
w('        };')
w('')
w('        private static readonly string[] Part2Notes =')
w('        {')
for n, _, note in p2:
    if note:
        w('            %s, %s,' % (json.dumps(str(n)), json.dumps(note)))
w('        };')
w('    }')
w('}')
open(sys.argv[1], 'w', encoding='utf-8', newline='\n').write('\n'.join(out) + '\n')
print('part1', len(p1), 'part2', len(p2), 'notes', sum(1 for r in p1 if r[2]) + sum(1 for r in p2 if r[2]))
