using UnityEngine;

namespace MaverickFresh
{
    public enum MavAimInputMode
    {
        CursorPosition = 0,
        LockedMouseDelta = 1
    }

    /// <summary>
    /// Fresh MouseFlight-style camera and aim rig.
    ///
    /// v0.8:
    /// - camera roll is no longer 100% tied to aircraft roll
    /// - horizon-stabilized camera base rotation added
    /// - free look still only while holding C / LeftAlt
    /// - far clip/render distance retained
    /// </summary>
    public class MavMouseFlightRig : MonoBehaviour
    {
        [Header("References")]
        public Transform aircraft;
        public Transform mouseAim;
        public Transform cameraRig;
        public Camera playerCamera;

        [Header("Aim Input")]
        public MavAimInputMode aimInputMode = MavAimInputMode.CursorPosition;
        public bool useFixed = false;
        public float mouseSensitivity = 3f;
        public float aimDistance = 850f;
        [Range(0.05f, 0.49f)] public float cursorAimLimit = 0.38f;
        public float cursorAimSmooth = 19f;
        public bool showCursorInCursorMode = true;
        public bool lockCursorInDeltaMode = true;

        [Header("Screen Aim Zones")]
        [Tooltip("If enabled, the jet only rolls when the cursor enters the outer left/right zones. The center corridor becomes pitch/yaw/aim only.")]
        public bool useScreenRollZones = true;
        [Range(0.02f, 0.45f)]
        [Tooltip("Half-width of the central no-roll corridor in viewport units. 0.22 means x=0.28~0.72 has no roll.")]
        public float rollNoRollHalfWidth = 0.22f;
        [Range(0.05f, 0.49f)]
        [Tooltip("Cursor x offset where roll reaches full strength.")]
        public float rollFullAtHalfWidth = 0.42f;
        [Range(0.5f, 3.0f)]
        public float rollZoneExponent = 1.25f;
        [Tooltip("Invert only the zone-generated roll command if left/right roll is reversed.")]
        public bool invertRollZone;
        [Tooltip("Runtime roll command generated by cursor screen zone.")]
        [Range(-1f, 1f)] public float screenRollCommand;
        public bool isInRollZone;

        [Space(8)]
        [Tooltip("If enabled, the jet uses upper/lower screen zones for pitch assist. Center horizontal band becomes stable/no-pitch corridor.")]
        public bool useScreenPitchZones = false;
        [Range(0.02f, 0.45f)]
        [Tooltip("Half-height of the central no-pitch corridor in viewport units. 0.16 means y=0.34~0.66 has little/no pitch assist.")]
        public float pitchNoPitchHalfHeight = 0.16f;
        [Range(0.05f, 0.49f)]
        [Tooltip("Cursor y offset where pitch reaches full strength.")]
        public float pitchFullAtHalfHeight = 0.40f;
        [Range(0.5f, 3.0f)]
        public float pitchZoneExponent = 1.20f;
        [Tooltip("Invert only the zone-generated pitch command if up/down pitch is reversed.")]
        public bool invertPitchZone;
        [Tooltip("Runtime pitch command generated by cursor screen zone. Positive means screen-up intent; Jet maps this to nose-up/down convention.")]
        [Range(-1f, 1f)] public float screenPitchCommand;
        public bool isInPitchZone;

        public Vector2 cursorOffsetFromCenter;

        [Header("Camera")]
        public float camSmoothSpeed = 10.5f;
        public Vector3 cameraLocalPosition = new Vector3(0f, 5.4f, -16.5f);
        public Vector3 cameraLocalEuler = Vector3.zero;
        public float cameraFov = 64f;
        public float zoomFov = 42f;
        public float fovSmooth = 4f;
        public float cameraNearClip = 0.08f;
        public float cameraFarClip = 24000f;
        [Tooltip("Keep this off for War Thunder-like behavior. If on, camera rotates toward aim even without free look.")]
        public bool cameraLooksAtAimWithoutFreeLook = false;
        public bool rightMouseZoom = true;

        [Header("v0.18.6 Camera Lag")]
        public bool useCameraLag = true;
        public float cameraPositionLag = 7f;
        public float cameraRotationLag = 8f;
        public float hardManeuverCameraLagMultiplier = 0.65f;
        public float maxCameraLagDistance = 6f;

        [Header("v0.18.6 Speed FOV")]
        public bool useSpeedBasedFov = true;
        public float minSpeedFov = 60f;
        public float cruiseSpeedFov = 68f;
        public float maxSpeedFov = 78f;
        public float fovSpeedMin = 80f;
        public float fovSpeedMax = 360f;

        [Header("v0.18.6 Camera Protection")]
        public bool useCameraCollisionAvoidance = true;
        public float cameraMinDistance = 9f;
        public float cameraMaxDistance = 18f;
        public float diveCameraPullback = 4f;
        public float steepDivePitchThreshold = -55f;
        public float cameraCollisionRadius = 0.8f;

        [Header("WarThunder-like Camera Stabilization")]
        [Range(0f, 1f)]
        [Tooltip("0 = camera horizon stays level; 1 = camera fully follows aircraft roll. Recommended 0.25~0.45.")]
        public float cameraRollFollowStrength = 0.30f;
        [Tooltip("When true, normal camera uses partial aircraft roll instead of fully inheriting roll.")]
        public bool stabilizeCameraHorizon = true;
        [Tooltip("Extra smoothing applied to roll-stabilized camera feel.")]
        public float horizonStabilizeSmooth = 12f;

        [Header("WarThunder-like Mouse Aim Camera Follow")]
        public bool useMouseAimCameraFollow = true;
        public float mouseAimCameraFollowStrength = 0.45f;
        public float mouseAimCameraFollowSmooth = 10.0f;
        public float mouseAimCameraMaxAngle = 30f;
        public bool disableMouseAimCameraFollowInFreeLook = true;
        public bool disableMouseAimCameraFollowInTGPFocus = true;
        [Tooltip("Use the cursor viewport offset directly for camera follow. This makes the view visibly move toward the mouse like War Thunder mouse aim.")]
        public bool useViewportOffsetCameraFollow = true;
        [Range(0f, 0.15f)] public float mouseAimCameraFollowDeadzone = 0.01f;
        public Vector2 mouseAimCameraViewportOffset;
        public string cameraFollowState = "ready";

        [Header("Free Look")]
        public KeyCode freeLookKey = KeyCode.C;
        public KeyCode freeLookAltKey = KeyCode.LeftAlt;
        public float freeLookSensitivity = 3f;
        public float maxFreeLookPitch = 70f;
        public float freeLookReturnSpeed = 9f;

        [Header("Runtime")]
        public bool isMouseAimFrozen;
        public bool freeLookHeld;
        public Vector3 frozenDirection = Vector3.forward;
        public Vector2 cursorViewport = new Vector2(0.5f, 0.5f);
        public float freeLookYaw;
        public float freeLookPitch;
        public bool showDebugInfo = false;
        public string rigState = "ready";

        public Vector3 BoresightPos
        {
            get
            {
                return aircraft == null
                    ? transform.forward * aimDistance
                    : aircraft.forward * aimDistance + aircraft.position;
            }
        }

        public Vector3 MouseAimPos
        {
            get
            {
                if (mouseAim == null)
                    return transform.forward * aimDistance;

                return isMouseAimFrozen
                    ? mouseAim.position + frozenDirection * aimDistance
                    : mouseAim.position + mouseAim.forward * aimDistance;
            }
        }

        public Vector3 VelocityVectorPos
        {
            get
            {
                if (aircraft == null)
                    return BoresightPos;

                Rigidbody rb = aircraft.GetComponent<Rigidbody>();
                if (rb == null || rb.linearVelocity.sqrMagnitude < 1f)
                    return BoresightPos;

                return aircraft.position + rb.linearVelocity.normalized * aimDistance;
            }
        }

        private void Awake()
        {
            if (aircraft == null)
                Debug.LogWarning(name + ": MavMouseFlightRig - aircraft not assigned.");

            EnsureRig();
            transform.parent = null;

            if (aircraft != null)
            {
                transform.position = aircraft.position;
                transform.rotation = aircraft.rotation;
                mouseAim.position = aircraft.position;
                mouseAim.rotation = aircraft.rotation;
                cameraRig.position = aircraft.position;
                cameraRig.rotation = GetCameraBaseRotation();
            }

            ConfigureCamera();
            frozenDirection = mouseAim != null ? mouseAim.forward : Vector3.forward;
            ApplyCursorMode();
        }

        private void OnEnable()
        {
            ApplyCursorMode();
            ConfigureCamera();
        }

        private void OnDisable()
        {
            Cursor.lockState = CursorLockMode.None;
            Cursor.visible = true;
        }

        private void Update()
        {
            ApplyCursorMode();

            if (!useFixed)
                UpdateCameraPos();

            RotateRigAndAim();
            UpdateCameraFov();
        }

        private void FixedUpdate()
        {
            if (useFixed)
                UpdateCameraPos();
        }

        public void CenterAim()
        {
            if (aircraft == null || mouseAim == null)
                return;

            cursorViewport = new Vector2(0.5f, 0.5f);
            mouseAim.position = aircraft.position;
            mouseAim.rotation = aircraft.rotation;
            frozenDirection = mouseAim.forward;
            isMouseAimFrozen = false;
            screenRollCommand = 0f;
            isInRollZone = false;
            cursorOffsetFromCenter = Vector2.zero;
            freeLookYaw = 0f;
            freeLookPitch = 0f;
        }

        private void EnsureRig()
        {
            if (mouseAim == null)
            {
                GameObject go = new GameObject("MouseAim");
                go.transform.SetParent(transform, false);
                mouseAim = go.transform;
            }

            if (cameraRig == null)
            {
                GameObject go = new GameObject("CameraRig");
                go.transform.SetParent(transform, false);
                cameraRig = go.transform;
            }

            if (playerCamera == null)
                playerCamera = Camera.main;
        }

        private void ConfigureCamera()
        {
            if (playerCamera == null)
                return;

            playerCamera.transform.SetParent(cameraRig, false);
            playerCamera.transform.localPosition = cameraLocalPosition;
            playerCamera.transform.localRotation = Quaternion.Euler(cameraLocalEuler);
            playerCamera.fieldOfView = cameraFov;
            playerCamera.nearClipPlane = cameraNearClip;
            playerCamera.farClipPlane = cameraFarClip;
            playerCamera.depth = 100;
            playerCamera.enabled = true;
        }

        private void ApplyCursorMode()
        {
            if (aimInputMode == MavAimInputMode.CursorPosition)
            {
                Cursor.lockState = CursorLockMode.None;
                Cursor.visible = showCursorInCursorMode;
            }
            else
            {
                Cursor.lockState = lockCursorInDeltaMode ? CursorLockMode.Locked : CursorLockMode.None;
                Cursor.visible = !lockCursorInDeltaMode;
            }
        }

        private void RotateRigAndAim()
        {
            if (mouseAim == null || cameraRig == null || playerCamera == null || aircraft == null)
                return;

            bool freeLookDown = MavFreshInput.GetKeyDown(freeLookKey) || MavFreshInput.GetKeyDown(freeLookAltKey);
            freeLookHeld = MavFreshInput.GetKey(freeLookKey) || MavFreshInput.GetKey(freeLookAltKey);
            bool freeLookUp = MavFreshInput.GetKeyUp(freeLookKey) || MavFreshInput.GetKeyUp(freeLookAltKey);

            if (freeLookDown)
            {
                isMouseAimFrozen = true;
                frozenDirection = mouseAim.forward;
                freeLookYaw = 0f;
                freeLookPitch = 0f;
                rigState = "free_look_freeze";
            }
            else if (freeLookUp)
            {
                isMouseAimFrozen = false;
                mouseAim.forward = frozenDirection;
                rigState = "free_look_release";
            }

            if (MavFreshInput.GetKeyDown(KeyCode.Mouse2))
            {
                CenterAim();
                rigState = "recenter";
            }

            if (!isMouseAimFrozen)
            {
                if (aimInputMode == MavAimInputMode.CursorPosition)
                    UpdateMouseAimFromCursor();
                else
                    UpdateMouseAimFromDelta();
            }

            Quaternion targetCameraRotation;

            if (freeLookHeld)
            {
                freeLookYaw += MavFreshInput.MouseX() * freeLookSensitivity;
                freeLookPitch -= MavFreshInput.MouseY() * freeLookSensitivity;
                freeLookPitch = Mathf.Clamp(freeLookPitch, -maxFreeLookPitch, maxFreeLookPitch);

                // Free-look is based on stabilized aircraft camera, not raw full-roll aircraft rotation.
                targetCameraRotation = GetCameraBaseRotation() * Quaternion.Euler(freeLookPitch, freeLookYaw, 0f);
                rigState = "free_look_camera";
            }
            else
            {
                float t = 1f - Mathf.Exp(-freeLookReturnSpeed * Time.deltaTime);
                freeLookYaw = Mathf.Lerp(freeLookYaw, 0f, t);
                freeLookPitch = Mathf.Lerp(freeLookPitch, 0f, t);

                if (cameraLooksAtAimWithoutFreeLook)
                {
                    Vector3 dir = (MouseAimPos - cameraRig.position).normalized;
                    if (dir.sqrMagnitude > 0.001f)
                        targetCameraRotation = Quaternion.LookRotation(dir, GetCameraUpVector());
                    else
                        targetCameraRotation = GetCameraBaseRotation();
                }
                else
                {
                    targetCameraRotation = GetCameraBaseRotation();
                    targetCameraRotation = ApplyMouseAimCameraFollow(targetCameraRotation);
                    if (!isMouseAimFrozen)
                        rigState = aimInputMode == MavAimInputMode.CursorPosition ? "cursor_aim_camera_follow" : "delta_aim_camera_follow";
                }
            }

            float smooth = stabilizeCameraHorizon ? horizonStabilizeSmooth : camSmoothSpeed;
            if (useCameraLag && !freeLookHeld)
            {
                float hardT = GetHardManeuverCameraT();
                smooth = cameraRotationLag * Mathf.Lerp(1f, hardManeuverCameraLagMultiplier, hardT);
            }

            if (!freeLookHeld && (cameraFollowState == "viewport_follow" || cameraFollowState == "aim_follow"))
                smooth = useCameraLag
                    ? Mathf.Min(smooth, mouseAimCameraFollowSmooth)
                    : mouseAimCameraFollowSmooth;

            cameraRig.rotation = Damp(cameraRig.rotation, targetCameraRotation, smooth, Time.deltaTime);
        }

        private Quaternion ApplyMouseAimCameraFollow(Quaternion baseRotation)
        {
            if (!useMouseAimCameraFollow || mouseAim == null || cameraRig == null)
            {
                cameraFollowState = "off";
                return baseRotation;
            }

            if (disableMouseAimCameraFollowInFreeLook && freeLookHeld)
            {
                cameraFollowState = "free_look_disabled";
                return baseRotation;
            }

            if (disableMouseAimCameraFollowInTGPFocus && IsTGPFullscreenOrFocusActive())
            {
                cameraFollowState = "tgp_disabled";
                return baseRotation;
            }

            Quaternion desired;

            if (useViewportOffsetCameraFollow)
            {
                // Previous v0.18 code blended toward MouseAimPos, but because MouseAim itself is
                // generated from the camera ray, the visible camera response could become too weak.
                // This path uses the actual screen cursor offset, so the camera reliably leans
                // toward the mouse direction like War Thunder's mouse-aim view.
                Vector2 center = new Vector2(0.5f, 0.5f);
                Vector2 offset = cursorViewport - center;
                mouseAimCameraViewportOffset = offset;

                if (offset.magnitude <= mouseAimCameraFollowDeadzone)
                {
                    cameraFollowState = "center";
                    return baseRotation;
                }

                float limit = Mathf.Max(0.001f, cursorAimLimit);
                float x = Mathf.Clamp(offset.x / limit, -1f, 1f);
                float y = Mathf.Clamp(offset.y / limit, -1f, 1f);

                float max = Mathf.Max(0f, mouseAimCameraMaxAngle);
                float strength = Mathf.Clamp01(mouseAimCameraFollowStrength);
                float yawOffset = x * max * strength;
                float pitchOffset = -y * max * strength;

                desired = baseRotation * Quaternion.Euler(pitchOffset, yawOffset, 0f);
                cameraFollowState = "viewport_follow";
            }
            else
            {
                Vector3 toAim = MouseAimPos - cameraRig.position;
                if (toAim.sqrMagnitude < 0.001f)
                {
                    cameraFollowState = "no_aim";
                    return baseRotation;
                }

                Vector3 baseForward = baseRotation * Vector3.forward;
                Vector3 desiredDir = toAim.normalized;
                float angle = Vector3.Angle(baseForward, desiredDir);
                if (angle > mouseAimCameraMaxAngle)
                    desiredDir = Vector3.Slerp(baseForward, desiredDir, mouseAimCameraMaxAngle / Mathf.Max(0.001f, angle)).normalized;

                desired = Quaternion.LookRotation(desiredDir, GetCameraUpVector());
                desired = Quaternion.Slerp(baseRotation, desired, Mathf.Clamp01(mouseAimCameraFollowStrength));
                cameraFollowState = "aim_follow";
            }

            // Return the full target rotation. RotateRigAndAim already damps cameraRig.rotation
            // toward this target, so applying another tiny Slerp here made v0.18 almost invisible.
            return desired;
        }

        private bool IsTGPFullscreenOrFocusActive()
        {
            MavTargetingPodSystem pod = FindObjectOfType<MavTargetingPodSystem>();
            if (pod == null)
                return false;

            return pod.displayMode == MavTargetingPodDisplayMode.Fullscreen;
        }

        private Quaternion GetCameraBaseRotation()
        {
            if (aircraft == null)
                return transform.rotation;

            if (!stabilizeCameraHorizon)
                return aircraft.rotation;

            Vector3 forward = aircraft.forward;
            Vector3 up = GetCameraUpVector();

            if (forward.sqrMagnitude < 0.001f)
                forward = Vector3.forward;

            if (Vector3.Cross(forward, up).sqrMagnitude < 0.001f)
                up = aircraft.up;

            return Quaternion.LookRotation(forward.normalized, up.normalized);
        }

        private Vector3 GetCameraUpVector()
        {
            if (aircraft == null || !stabilizeCameraHorizon)
                return Vector3.up;

            Vector3 up = Vector3.Slerp(Vector3.up, aircraft.up, Mathf.Clamp01(cameraRollFollowStrength));
            if (up.sqrMagnitude < 0.001f)
                up = Vector3.up;

            return up.normalized;
        }

        private void UpdateMouseAimFromCursor()
        {
            Vector2 mousePos = MavFreshInput.MousePosition();

            float x = Mathf.Clamp(mousePos.x / Mathf.Max(1f, Screen.width), 0f, 1f);
            float y = Mathf.Clamp(mousePos.y / Mathf.Max(1f, Screen.height), 0f, 1f);

            Vector2 center = new Vector2(0.5f, 0.5f);
            Vector2 offset = new Vector2(x, y) - center;

            if (offset.magnitude > cursorAimLimit)
                offset = offset.normalized * cursorAimLimit;

            cursorViewport = center + offset;
            UpdateScreenAimZones();

            Ray ray = playerCamera.ViewportPointToRay(new Vector3(cursorViewport.x, cursorViewport.y, 0f));
            Vector3 desired = ray.direction.normalized;

            if (desired.sqrMagnitude < 0.001f)
                desired = aircraft != null ? aircraft.forward : transform.forward;

            float t = 1f - Mathf.Exp(-cursorAimSmooth * Time.deltaTime);
            mouseAim.forward = Vector3.Slerp(mouseAim.forward, desired, t);
        }

        private void UpdateScreenAimZones()
        {
            Vector2 center = new Vector2(0.5f, 0.5f);
            cursorOffsetFromCenter = cursorViewport - center;

            // Horizontal roll zones.
            if (!useScreenRollZones)
            {
                isInRollZone = false;
                screenRollCommand = 0f;
            }
            else
            {
                float absX = Mathf.Abs(cursorOffsetFromCenter.x);
                float signX = Mathf.Sign(cursorOffsetFromCenter.x);

                if (absX <= rollNoRollHalfWidth)
                {
                    isInRollZone = false;
                    screenRollCommand = 0f;
                }
                else
                {
                    isInRollZone = true;
                    float t = Mathf.InverseLerp(rollNoRollHalfWidth, Mathf.Max(rollNoRollHalfWidth + 0.001f, rollFullAtHalfWidth), absX);
                    t = Mathf.Clamp01(t);
                    t = Mathf.Pow(t, rollZoneExponent);

                    screenRollCommand = Mathf.Clamp(signX * t, -1f, 1f);
                    if (invertRollZone)
                        screenRollCommand = -screenRollCommand;
                }
            }

            // Vertical pitch zones.
            if (!useScreenPitchZones)
            {
                isInPitchZone = false;
                screenPitchCommand = 0f;
            }
            else
            {
                float absY = Mathf.Abs(cursorOffsetFromCenter.y);
                float signY = Mathf.Sign(cursorOffsetFromCenter.y);

                if (absY <= pitchNoPitchHalfHeight)
                {
                    isInPitchZone = false;
                    screenPitchCommand = 0f;
                }
                else
                {
                    isInPitchZone = true;
                    float t = Mathf.InverseLerp(pitchNoPitchHalfHeight, Mathf.Max(pitchNoPitchHalfHeight + 0.001f, pitchFullAtHalfHeight), absY);
                    t = Mathf.Clamp01(t);
                    t = Mathf.Pow(t, pitchZoneExponent);

                    screenPitchCommand = Mathf.Clamp(signY * t, -1f, 1f);
                    if (invertPitchZone)
                        screenPitchCommand = -screenPitchCommand;
                }
            }
        }

        private void UpdateMouseAimFromDelta()
        {
            float mouseX = MavFreshInput.MouseX() * mouseSensitivity;
            float mouseY = -MavFreshInput.MouseY() * mouseSensitivity;

            Transform cam = playerCamera.transform;
            mouseAim.Rotate(cam.right, mouseY, Space.World);
            mouseAim.Rotate(cam.up, mouseX, Space.World);
        }

        private void UpdateCameraPos()
        {
            if (aircraft != null)
                transform.position = aircraft.position;

            if (mouseAim != null && aircraft != null)
                mouseAim.position = aircraft.position;

            if (cameraRig != null && aircraft != null)
            {
                Vector3 desiredRigPosition = aircraft.position;

                if (useCameraLag)
                {
                    float hardT = GetHardManeuverCameraT();
                    float lag = cameraPositionLag * Mathf.Lerp(1f, hardManeuverCameraLagMultiplier, hardT);
                    float t = 1f - Mathf.Exp(-lag * Time.deltaTime);
                    cameraRig.position = Vector3.Lerp(cameraRig.position, desiredRigPosition, t);

                    Vector3 offset = cameraRig.position - desiredRigPosition;
                    float maxLag = Mathf.Max(0f, maxCameraLagDistance);
                    if (maxLag > 0f && offset.magnitude > maxLag)
                        cameraRig.position = desiredRigPosition + offset.normalized * maxLag;
                }
                else
                {
                    cameraRig.position = desiredRigPosition;
                }
            }

            UpdateCameraLocalPosition();
        }

        private void UpdateCameraFov()
        {
            if (playerCamera == null)
                return;

            float targetFov = cameraFov;
            if (useSpeedBasedFov && aircraft != null)
            {
                Rigidbody rb = aircraft.GetComponent<Rigidbody>();
                if (rb != null)
                {
                    float speed = rb.linearVelocity.magnitude;
                    float cruiseSpeed = Mathf.Lerp(fovSpeedMin, fovSpeedMax, 0.5f);
                    MavMouseFlightJet jet = aircraft.GetComponent<MavMouseFlightJet>();
                    if (jet != null)
                        cruiseSpeed = Mathf.Clamp(jet.targetCruiseSpeed, fovSpeedMin + 1f, fovSpeedMax - 1f);

                    if (speed <= cruiseSpeed)
                    {
                        float lowT = Mathf.InverseLerp(fovSpeedMin, cruiseSpeed, speed);
                        targetFov = Mathf.Lerp(minSpeedFov, cruiseSpeedFov, lowT);
                    }
                    else
                    {
                        float highT = Mathf.InverseLerp(cruiseSpeed, Mathf.Max(cruiseSpeed + 1f, fovSpeedMax), speed);
                        targetFov = Mathf.Lerp(cruiseSpeedFov, maxSpeedFov, highT);
                    }
                }
            }

            if (rightMouseZoom && MavFreshInput.GetKey(KeyCode.Mouse1))
                targetFov = zoomFov;

            float t = 1f - Mathf.Exp(-fovSmooth * Time.deltaTime);
            playerCamera.fieldOfView = Mathf.Lerp(playerCamera.fieldOfView, targetFov, t);
            playerCamera.nearClipPlane = cameraNearClip;
            playerCamera.farClipPlane = cameraFarClip;
        }

        private void UpdateCameraLocalPosition()
        {
            if (playerCamera == null || cameraRig == null)
                return;

            Vector3 desiredLocal = cameraLocalPosition;
            if (useCameraCollisionAvoidance && aircraft != null)
            {
                float baseDistance = Mathf.Clamp(Mathf.Abs(cameraLocalPosition.z), cameraMinDistance, cameraMaxDistance);
                float pitchAngle = Mathf.Asin(Mathf.Clamp(aircraft.forward.y, -1f, 1f)) * Mathf.Rad2Deg;
                float diveT = Mathf.InverseLerp(steepDivePitchThreshold, -90f, pitchAngle);
                float targetDistance = Mathf.Clamp(baseDistance + diveCameraPullback * diveT, cameraMinDistance, cameraMaxDistance + diveCameraPullback);
                desiredLocal.z = -targetDistance;

                Vector3 desiredWorld = cameraRig.TransformPoint(desiredLocal);
                Vector3 fromAircraft = desiredWorld - aircraft.position;
                float desiredDistance = fromAircraft.magnitude;
                if (desiredDistance > cameraMinDistance && fromAircraft.sqrMagnitude > 0.001f)
                {
                    Vector3 direction = fromAircraft.normalized;
                    Vector3 castOrigin = aircraft.position + direction * cameraMinDistance;
                    float castLength = desiredDistance - cameraMinDistance;
                    RaycastHit hit;
                    if (Physics.SphereCast(castOrigin, cameraCollisionRadius, direction, out hit, castLength, ~0, QueryTriggerInteraction.Ignore))
                    {
                        float protectedDistance = cameraMinDistance + Mathf.Max(0f, hit.distance - cameraCollisionRadius);
                        desiredWorld = aircraft.position + direction * protectedDistance;
                        desiredLocal = cameraRig.InverseTransformPoint(desiredWorld);
                    }
                }
            }

            float lag = useCameraLag ? Mathf.Max(0.01f, cameraPositionLag) : 40f;
            float t = 1f - Mathf.Exp(-lag * Time.deltaTime);
            playerCamera.transform.localPosition = Vector3.Lerp(playerCamera.transform.localPosition, desiredLocal, t);
            playerCamera.transform.localRotation = Quaternion.Euler(cameraLocalEuler);
        }

        private float GetHardManeuverCameraT()
        {
            if (aircraft == null)
                return 0f;

            Rigidbody rb = aircraft.GetComponent<Rigidbody>();
            if (rb == null)
                return 0f;

            float velocityAngle = rb.linearVelocity.sqrMagnitude > 1f
                ? Vector3.Angle(aircraft.forward, rb.linearVelocity.normalized)
                : 0f;
            float angularRateDeg = rb.angularVelocity.magnitude * Mathf.Rad2Deg;

            float angleT = Mathf.InverseLerp(12f, 55f, velocityAngle);
            float rateT = Mathf.InverseLerp(40f, 160f, angularRateDeg);
            return Mathf.Clamp01(Mathf.Max(angleT, rateT));
        }

        private Quaternion Damp(Quaternion a, Quaternion b, float lambda, float dt)
        {
            return Quaternion.Slerp(a, b, 1f - Mathf.Exp(-lambda * dt));
        }

        private void OnDrawGizmos()
        {
            if (!showDebugInfo)
                return;

            Color old = Gizmos.color;

            if (aircraft != null)
            {
                Gizmos.color = Color.white;
                Gizmos.DrawWireSphere(BoresightPos, 10f);
            }

            if (mouseAim != null)
            {
                Gizmos.color = Color.red;
                Gizmos.DrawWireSphere(MouseAimPos, 10f);
                Gizmos.color = Color.blue;
                Gizmos.DrawRay(mouseAim.position, mouseAim.forward * 50f);
            }

            Gizmos.color = old;
        }
    }
}
